namespace FET {

    export enum SignWorkflowState {
        CONFIGURING,
        CREATING_SESSION,
        RETRIEVING_SESSION,
        FILE_SELECTION,
        UPLOADING_FILE,
        ASKING_FOR_MORE_FILES,
        SIGN_METHOD_SELECTION,
        INITIALIZING_ASOL,
        CONFIGURE_ARSS,
        SIGNING,
        CONFIGURE_ASOL,
        ASOL_PREPARING_FILES,
        ASOL_SIGNING,
        ASOL_FINALIZING_SIGNATURE,
        SIGN_CHANNEL_SELECTION,
        CONFIGURE_EXSYST_CHANNEL,
        EXSYST_PREPARING_FILES,
        EXSYST_UPLODAD_FILES,
        EXSYST_TYPOLOGY_SELECTION,
        EXSYST_FINALIZING_SIGNATURE,
        COMPLETED_EXSYST,
        COMPLETED,
    }

}
